spring:
  flyway:
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true

server:
  servlet:
    context-path: /air-ticket-booking
  port: 8081

jwt:
  secret:
    key: 7639792442264528482B4D6251655468576D5A7134743777217A25432A462D4A
