CREATE TABLE IF NOT EXISTS flights
(
    id          VARCHAR(255)     NOT NULL,
    origin      VARCHAR(255),
    destination VARCHAR(255),
    departure   TIMESTAMP WITHOUT TIME ZONE,
    arrival     TIMESTAMP WITHOUT TIME ZONE,
    price       DOUBLE PRECISION NOT NULL,
    fare_class  VARCHAR(255),
    carrier     VARCHAR(255),
    CONSTRAINT pk_flights PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS payments
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner  VARCHAR(255),
    sum    DOUBLE PRECISION                        NOT NULL,
    date   TIMESTAMP WITHOUT TIME ZONE,
    status VARCHAR(255),
    CONSTRAINT pk_payments PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    email     VARCHAR(255),
    password  VARCHAR(255),
    role      VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
    );

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

CREATE TABLE IF NOT EXISTS tickets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner      VARCHAR(255),
    seat       VARCHAR(255),
    payment_id BIGINT,
    user_id    BIGINT,
    flight_id  VARCHAR(255),
    CONSTRAINT pk_tickets PRIMARY KEY (id)
    );

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_FLIGHT FOREIGN KEY (flight_id) REFERENCES flights (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payments (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

